### ISSUE TITLE
Fields for some models

### ISSUE THREAD

**Issue by MargaridaBSC** [ESGF/sproket#1]
Hello,

When I try to extract the fields for some models of the CMIP5 project, an error appears. For example, for the model MIROC-ESM and the monthly variable pr:
```
./sproket -field.keys cmip5_historical_MIROC-ESM_monthly_pr.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x608f92]
goroutine 1 [running]:
net/http.(*Client).deadline(0x0, 0xc0000aa028, 0x1ffffffffffff, 0xf8)
	/usr/local/go/src/net/http/client.go:187 +0x22
net/http.(*Client).do(0x0, 0xc000106000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:527 +0xab
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:509
sproket.(*Search).Get(0xc000100048, 0xc0000cc0a0, 0x4e, 0x7469c0, 0xc00008ec30, 0x0, 0x0)
	/Users/carlson60/go/src/sproket/retrieve.go:21 +0x1a9
sproket.(*Search).performSearch(0xc000100048, 0xc000087cb8, 0x6e8823, 0x5, 0xc000087e10, 0xc000098f70, 0x8)
	/Users/carlson60/go/src/sproket/search.go:100 +0x348
sproket.(*Search).GetFields(0xc000100048, 0x0, 0x0, 0xc00006cb08)
	/Users/carlson60/go/src/sproket/fields.go:27 +0x27b
main.outputFields(0xc000100000)
	/Users/carlson60/go/src/sproket/cmd/sproket/main.go:343 +0x4b
main.main()
	/Users/carlson60/go/src/sproket/cmd/sproket/main.go:484 +0x683
```
How could this be solved?

I also add the JSON content:
```
{
"search_api": "https://esgf-node.llnl.gov/esg-search/search/",
"data_node_priority": ["aims3.llnl.gov", "esgf-data1.llnl.gov", "esgf.nci.org.au", "esgf-data1.diasjp.net"],
"fields": {
"variable_id": "pr",
"experiment": "historical",
"time_frequency": "mon",
"model": "MIROC-ESM",
"project": "CMIP5"
}
}
```

Thank you very much in advance.

**Comment by nathanlcarlson** [comment]
Hi @MargaridaBSC , it looks like you did not specify the `-config` flag before the path to your configuration file.

This should be handled better, though, to inform the user when they miss `-config`. I am working on a fix now.

Thanks for the report!

**Comment by nathanlcarlson** [comment]
Hi @MargaridaBSC, you will also want to use `-unsafe` as some of the files in the CMIP5 catalog do not have the expected fields that indicate if the file was retracted or if it is the latest, meaning they cannot be found without using `-unsafe`.

Also, it looks like the variable field is simply `variable`, not `variable_id` for CMIP5, hope that helps. Thanks.

**Comment by nathanlcarlson** [comment]
I release v0.2.14 that fixes the logic around checking if the config is specified or not. Also, use `-unsafe` at your own risk.

**Comment by MargaridaBSC** [comment]
Hi @nathanlcarlson,

Thank you very much for your kind answer. I changed  `variable_id` to `variable` and now it works correctly.

Best regards,
Margarida
